# PATHS

input_vcf: "/shares/CIBIO-Storage/BCG/scratch/fgastaldello/data/cvep-plm/{cancer_type}/vcf/{cancer_type}.{variant_type}.recalibrated_99.9.vcf"
data_folder: "/shares/CIBIO-Storage/BCG/scratch/fgastaldello/data/cvep-plm"
recombination_maps: "/shares/CIBIO-Storage/BCG/scratch/fgastaldello/resources/maps"
shapeit5: "/shares/CIBIO-Storage/BCG/scratch/fgastaldello/tools/shapeit5/phase_common_static"


# WILDCARDS

variant_types: ["snp", "indel"]
cancer_types: ["UVM"]