# PATHS

input_vcf: "/shares/CIBIO-Storage/BCG/scratch/fgastaldello/data/cvep-plm/{cancer_type}/vcf/{cancer_type}.{variant_type}.recalibrated_99.9.vcf"
data_folder: "/shares/CIBIO-Storage/BCG/scratch/fgastaldello/data/cvep-plm"

# WILDCARDS

variant_types: ["snp", "indel"]
cancer_types: ["UVM"]