# PATHS

input_vcf: "/shares/CIBIO-Storage/BCG/scratch/TCGA-GATK/{cancer_type}.{variant_type}.recalibrated_99.9.vcf"
data_folder: "/shares/CIBIO-Storage/BCG/scratch/fgastaldello/data/MutSeqGenerator"
recombination_maps: "/shares/CIBIO-Storage/BCG/scratch/fgastaldello/resources/maps"
shapeit5: "/shares/CIBIO-Storage/BCG/scratch/fgastaldello/tools/shapeit5/phase_common_static"
wt_sequences: "/shares/CIBIO-Storage/BCG/scratch/fgastaldello/resources/protein_coding_transcripts"


# WILDCARDS

variant_types: ["snp", "indel"]
cancer_types: ["UVM","DLBC","ACC","BLCA","BRCA","CESC","CHOL","COAD","ESCA","GBM","HNSC","KICH","KIRC","KIRP","LAML","LGG","LIHC","LUAD","LUSC","MESO","OV","PAAD","PCPG","PRAD","READ","SARC","SKCM","STAD","TGCT","THCA","THYM","UCEC","UCS"]
# "UVM","DLBC","ACC","BLCA","BRCA","CESC","CHOL","COAD","ESCA","GBM","HNSC","KICH","KIRC","KIRP","LAML","LGG","LIHC","LUAD","LUSC","MESO","OV","PAAD","PCPG","PRAD","READ","SARC","SKCM","STAD","TGCT","THCA","THYM","UCEC","UCS"

# PARALLEL CORES
#
# Always check that cores*jobs < available cores on machine (Snakemake should take care of that, but... )
bcftools_threads: 2                   # 22 jobs at same time
extract_genotype_cores: 5             # 22 jobs at same time   
